{
  "category": "Control",
  "name": "TRY_CATCH",
  "tests": [
    {
      "name": "try catch without exception",
      "script": [
        "TRY",
        "0x0500",
        "PUSH0",
        "ENDT",
        "PUSH3",
        "ENDC"
      ],
      "steps": [
        {
          "actions": [
            "stepInto",
            "stepInto",
            "stepInto"
          ],
          "result": {
            "state": "BREAK",
            "invocationStack": [
              {
                "instructionPointer": 5,
                "nextInstruction": "PUSH3",
                "evaluationStack": [
                  {
                    "type": "integer",
                    "value": 0
                  }
                ]
              }
            ]
          }
        }
      ]
    },
    {
      "name": "try catch with exception",
      "script": [
        "TRY",
        "0x0500",
        "THROW",
        "ENDT",
        "PUSH1",
        "ENDC",
        "PUSH2"
      ],
      "steps": [
        {
          "actions": [
            "stepInto",
            "stepInto"
          ],
          "result": {
            "state": "BREAK",
            "invocationStack": [
              {
                "instructionPointer": 5,
                "nextInstruction": "PUSH1"
              }
            ]
          }
        },
        {
          "actions": [
            "stepInto",
            "stepInto"
          ],
          "result": {
            "state": "BREAK",
            "invocationStack": [
              {
                "instructionPointer": 7,
                "nextInstruction": "PUSH2",
                "evaluationStack": [
                  {
                    "type": "integer",
                    "value": 1
                  }
                ]
              }
            ]
          }
        }
      ]
    }
  ]
}
