{
  "category": "Control",
  "name": "TRY_CATCH_FINALLY",
  "tests": [
    {
      "name": "try{ try-catch } catch finally without exception",
      "script": [
        "TRY",
        "0x0b0e",
          "TRY",
          "0x0500",
            "THROW",
          "ENDT",
            "PUSH1",
          "ENDC",
        "ENDT",
        "RET",
          "PUSH2",
        "ENDC",
          "PUSH3",
        "ENDF",
          "PUSH4"
      ],
      "steps": [
        {
          "actions": [
            "stepInto",
            "stepInto",
            "stepInto"
          ],
          "result": {
            "state": "BREAK",
            "invocationStack": [
              {
                "instructionPointer": 8,
                "nextInstruction": "PUSH1"
              }
            ]
          }
        },
        {
          "actions": [
            "stepInto",
            "stepInto"
          ],
          "result": {
            "state": "BREAK",
            "invocationStack": [
              {
                "instructionPointer": 10,
                "nextInstruction": "ENDT",
                "evaluationStack": [
                  {
                    "type": "integer",
                    "value": 1
                  }
                ]
              }
            ]
          }
        },
        {
          "actions": [
            "stepInto",
            "stepInto",
            "stepInto"
          ],
          "result": {
            "state": "BREAK",
            "invocationStack": [
              {
                "instructionPointer": 11,
                "nextInstruction": "RET",
                "evaluationStack": [
                  {
                    "type": "integer",
                    "value": 3
                  },
                  {
                    "type": "integer",
                    "value": 1
                  }
                ]
              }
            ]
          }
        }
      ]
    }
  ]
}
