{
  "category": "Control",
  "name": "TRY_FINALLY",
  "tests": [
    {
      "name": "try finally with exception",
      "script": [
        "TRY",
        "0x0007",
        "THROW",
        "ENDT",
        "JMP",
        "0x03",
        "PUSH1",
        "ENDF",
        "PUSH2"
      ],
      "steps": [
        {
          "actions": [
            "stepInto",
            "stepInto"
          ],
          "result": {
            "state": "BREAK",
            "invocationStack": [
              {
                "instructionPointer": 7,
                "nextInstruction": "PUSH1"
              }
            ]
          }
        },
        {
          "actions": [
            "stepInto",
            "stepInto"
          ],
          "result": {
            "state": "FAULT",
            "invocationStack": [
              {
                "instructionPointer": 6,
                "nextInstruction": "PUSH2",
                "evaluationStack": [
                  {
                    "type": "integer",
                    "value": 1
                  }
                ]
              }
            ]
          }
        }
      ]
    }
  ]
}
