{
  "category": "Control",
  "name": "TRY_CATCH_FINALLY",
  "tests": [
    {
      "name": "try catch finally without exception",
      "script": [
        "TRY",
        "0x0608",
        "PUSH0",
        "ENDTRY",
        "RET",
        "PUSH2",
        "ENDTRY",
        "PUSH3",
        "ENDFINALLY",
        "PUSH4"
      ],
      "steps": [
        {
          "actions": [
            "stepInto",
            "stepInto",
            "stepInto"
          ],
          "result": {
            "state": "BREAK",
            "invocationStack": [
              {
                "instructionPointer": 8,
                "nextInstruction": "PUSH3",
                "evaluationStack": [
                  {
                    "type": "integer",
                    "value": 0
                  }
                ]
              }
            ]
          }
        },
        {
          "actions": [
            "stepInto",
            "stepInto"
          ],
          "result": {
            "state": "BREAK",
            "invocationStack": [
              {
                "instructionPointer": 5,
                "nextInstruction": "RET",
                "evaluationStack": [
                  {
                    "type": "integer",
                    "value": 3
                  },
                  {
                    "type": "integer",
                    "value": 0
                  }
                ]
              }
            ]
          }
        }
      ]
    }
  ]
}
